// ==============================================================
// File Name: CDInputMouse.h
// 
// Model Name: Treball de fi de Carrera
// 
// 
// Generated by Visual UML 2.9.1 at 17:18:01 on sábado, 29 de marzo de 2003
// 
// ==============================================================

#ifndef CDInputMouse_H
#define CDInputMouse_H

#include "CDirectInput.h"


//CDirectInput * tmp;
// Class Name: CDInputMouse
// See file: 'CDInputMouse.cpp' for the implementation of this class
// Generated by Visual UML 2.9.1 at 17:18:01 on sábado, 29 de marzo de 2003
BOOL CALLBACK DIEnumDevicesCallback(LPCDIDEVICEINSTANCE lpddi, LPVOID pvRef);
BOOL CALLBACK DIEnumDeviceComponentsCallback(LPCDIDEVICEOBJECTINSTANCE lpddoi, LPVOID pvRef);


class CDInputMouse : public CDirectInput {
// Operations:
	public:
	// public member functions
		CDInputMouse(HWND hwnd2, HINSTANCE hinst2);
	protected:
	// protected member functions:
		bool ConcreteCreate(GUID id_disp, DWORD Flags);
		void ConcreteMain();
		void ConcreteMoreAxis();
		void  ConcreteMoreButtons();

		//DIMOUSESTATE2 mousestate;
};

#endif // CDInputMouse_H
