// ==============================================================
// File Name: CDInputJoystick.h
// 
// Model Name: Treball de fi de Carrera
// 
// Model Location: C:\Jsm\Carrera\TfiCarrera\Treball de fi de Carrera.Uml
// 
// 
// ==============================================================

#ifndef CDInputJoystick_H
#define CDInputJoystick_H

#include "CDirectInput.h"

#define JOYMAX 10000
#define JOYMIN -10000
#define JOYDEAD 2000
#define JOYSAT  9500

// Class Name: CDInputJoystick
// See file: 'CDInputJoystick.cpp' for the implementation of this class
// Generated by Visual UML 2.9.1 at 17:18:01 on sábado, 29 de marzo de 2003
BOOL CALLBACK DIEnumDevicesCallback(LPCDIDEVICEINSTANCE lpddi, LPVOID pvRef);
BOOL CALLBACK DIEnumDeviceComponentsCallback(LPCDIDEVICEOBJECTINSTANCE lpddoi, LPVOID pvRef);


class CDInputJoystick : public CDirectInput {
// Operations:
	public:
	// public member functions:
	CDInputJoystick(HWND hwnd2, HINSTANCE hinst2);

	protected:
	// protected member functions:
	bool ConcreteCreate(GUID id_disp, DWORD Flags);
	void ConcreteMain();
	void ConcreteMoreAxis();
	void  ConcreteMoreButtons();		
};

#endif // CDInputJoystick_H
